[build-system]
requires = ["setuptools ~= 58.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Swift Banker"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "fastapi"
]